### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by HynekBaran** [felias-fogg/OneWire#1]
Hi,
I am sorry for disturbing you. Your library seemed very nice (and important) to me, but unfortunately, it does not work. 
More specifically, I used m328 on breadboard using 1 MHz internal clock and connected Dallas DS18B20 but no onewire device was found.
Any chance to get it work? :)
Thanks,
Hynek Baran

**Comment by felias-fogg** [comment]
Works perfectly for me. Did you make sure that the Arduino IDE was aware that you ran the m328 on 1MHz? You need to define the appropriate board in boards.txt with all the right parameters.
